### ISSUE TITLE
App Build showing blank screen

### ISSUE THREAD

**Issue by mohsinht** [apppresser/AppPresser#16]
Hello Thiessen, I just created an app with Apppresser (Agency Package). It looks fine in myapppresser preview and the mobile preview but when I download an apk build from phonegap, it doesn't work. It shows splash screen and then it shows a white blank screen.
I've updated config.xml file with these lines:
`<preference name="SplashScreenDelay" value="10000" />`
`<preference name="AutoHideSplashScreen" value="true" />`
but the problem is still there.
I also submitted a build to Itunes which got rejected immediately. Please help me fix this issue.

Thanks.

**Comment by stillatmylinux** [comment]
Since you purchased the Agency Package you can get support at https://apppresser.com/contact/.

It's possible that one of your menu items is pointing to a missing page giving you a 404 error.  This can cause a white screen.  Otherwise, if you haven't rebuilt your app lately you can try rebuilding your app at myapppresser.com, you may have some outdated code.  Otherwise, please fill out a support ticket and we can take a closer look.
